version: "2"
linters:
  default: "all"
  settings:
    exhaustruct:
      exclude:
        - '^net/http\.Server$'
        - '^go\.uber\.org/zap\.Config$'
        - '.*kgo\.Record.*'
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      min-name-length: 1
  disable:
    - nlreturn
    - depguard