// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ch-6/proto/recent_change.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecentChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Bot           bool                   `protobuf:"varint,2,opt,name=bot,proto3" json:"bot,omitempty"`
	ServerUrl     string                 `protobuf:"bytes,3,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentChange) Reset() {
	*x = RecentChange{}
	mi := &file_ch_6_proto_recent_change_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentChange) ProtoMessage() {}

func (x *RecentChange) ProtoReflect() protoreflect.Message {
	mi := &file_ch_6_proto_recent_change_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentChange.ProtoReflect.Descriptor instead.
func (*RecentChange) Descriptor() ([]byte, []int) {
	return file_ch_6_proto_recent_change_proto_rawDescGZIP(), []int{0}
}

func (x *RecentChange) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RecentChange) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *RecentChange) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

var File_ch_6_proto_recent_change_proto protoreflect.FileDescriptor

const file_ch_6_proto_recent_change_proto_rawDesc = "" +
	"\n" +
	"\x1ech-6/proto/recent_change.proto\x12\twikimedia\"S\n" +
	"\fRecentChange\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03bot\x18\x02 \x01(\bR\x03bot\x12\x1d\n" +
	"\n" +
	"server_url\x18\x03 \x01(\tR\tserverUrlB:Z8github.com/codyonesock/backend_learning/ch-6/proto;protob\x06proto3"

var (
	file_ch_6_proto_recent_change_proto_rawDescOnce sync.Once
	file_ch_6_proto_recent_change_proto_rawDescData []byte
)

func file_ch_6_proto_recent_change_proto_rawDescGZIP() []byte {
	file_ch_6_proto_recent_change_proto_rawDescOnce.Do(func() {
		file_ch_6_proto_recent_change_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ch_6_proto_recent_change_proto_rawDesc), len(file_ch_6_proto_recent_change_proto_rawDesc)))
	})
	return file_ch_6_proto_recent_change_proto_rawDescData
}

var file_ch_6_proto_recent_change_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ch_6_proto_recent_change_proto_goTypes = []any{
	(*RecentChange)(nil), // 0: wikimedia.RecentChange
}
var file_ch_6_proto_recent_change_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ch_6_proto_recent_change_proto_init() }
func file_ch_6_proto_recent_change_proto_init() {
	if File_ch_6_proto_recent_change_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ch_6_proto_recent_change_proto_rawDesc), len(file_ch_6_proto_recent_change_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ch_6_proto_recent_change_proto_goTypes,
		DependencyIndexes: file_ch_6_proto_recent_change_proto_depIdxs,
		MessageInfos:      file_ch_6_proto_recent_change_proto_msgTypes,
	}.Build()
	File_ch_6_proto_recent_change_proto = out.File
	file_ch_6_proto_recent_change_proto_goTypes = nil
	file_ch_6_proto_recent_change_proto_depIdxs = nil
}
