apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer:latest
        imagePullPolicy: Never # Local testing
        ports:
        - containerPort: 2113
        env:
        - name: PORT
          value: ":2113"
        - name: STREAM_URL
          value: "https://stream.wikimedia.org/v2/stream/recentchange"
        - name: LOG_LEVEL
          value: "INFO"
        - name: JWT_SECRET
          value: "super-secure-random-key"
        - name: USE_SCYLLA
          value: "TRUE"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 2113
      targetPort: 2113